import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import I18nProvider from "@components/Organisms/I18nProvider";
import { ILocale } from "@infrastructure/i18n/get-dictionary";
import { getDictionary } from "@infrastructure/i18n/get-dictionary";
import TanstackProvider from "@components/Organisms/TanstackProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    template: "%s | Create Next App", //TODO: Chưa chuyển i18next & thay đổi tên app
    default: "Create Next App",
  },
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ lang: string }>;
}>) {
  const { lang } = await params;
  const dict = await getDictionary(lang as ILocale);

  return (
    <html lang={lang}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <I18nProvider lang={lang as ILocale} resources={dict}>
          <TanstackProvider>
            {children}
          </TanstackProvider>
        </I18nProvider>
      </body>
    </html>
  );
}
